apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-jqry
  namespace: jqry
spec:
  selector:
    matchLabels:
      app: jqry
  replicas: 5 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: jqry
    spec:
      containers:
      - name: jqry
        image: public.ecr.aws/h3u1y5t3/sample-jqry:latest

        ports:
        - containerPort: 80
